name: 'GitHub Syn'

on: [push]

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 'Config'
        run: |
          git clone https://github.com/seqyuan/sphinxbook.git
          cp -r sphinxbook/docs/* ./docs/
          rm -rf sphinxbook

      - name: 'Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          deploy_key: ${{ secrets.DORDEP }}
          publish_dir: ./docs

      - name: switch branch
        run: git checkout gh-pages

      - name: 'Mirror to github'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:seqyuan/anno_papaer.git
          ssh_private_key:
            ${{ secrets.GIT_SYN_KEY }}
