name: 'GitHub Syn'

on: [push]

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'conf'
        run: |
          git clone https://github.com/seqyuan/sphinxbook.git
          mv sphinxbook/docs/* docs/
          rm -r sphinxbook
      - name: 'Mirror to github'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:seqyuan/anno_papaer.git
          ssh_private_key:
            ${{ secrets.GIT_SYN_KEY }}

      - name: Setup Deploy Private Key
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.GIT_SYN_KEY }}  # 这里是上面anno-sc.github.io新增的公钥：HEXO_DEPLOY_KEY
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Setup Git Infomation # set git infomation
        run: |
          git config --global user.name 'seqyuan'
          git config --global user.email 'ahworld07@gmail.com'
      - name: deploy
        run: |
          git clone https://github.com/seqyuan/sphinxbook.git
          #git clone https://github.com/seqyuan/anno_papaer.git
          cp -r sphinxbook/docs/* ./docs
          rm -r sphinxbook
          #cp -r anno_papaer/docs/* ./docs
          #rm -r anno_papaer
          git remote add target https://github.com/seqyuan/paper_pages.git
          git add -A
          git commit -m "..."
          git push origin gh-pages
