name: 'GitHub Syn'

on: [push]

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to github'
        uses: pages-action@v1
        with:
          target_repo_url:
            git@github.com:seqyuan/anno_papaer.git
          ssh_private_key:
            ${{ secrets.GIT_SYN_KEY }}
