name: 'GitHub Syn'

on: [push]

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'conf'
        run: |
          git clone https://github.com/seqyuan/sphinxbook.git
          mv sphinxbook/docs/* docs/
          rm -r sphinxbook
      - name: 'Mirror to github'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:seqyuan/anno_papaer.git
          ssh_private_key:
            ${{ secrets.GIT_SYN_KEY }}
      - name: deploy
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_SYN_KEY }}
        run: |
          git clone https://github.com/seqyuan/sphinxbook.git
          git clone https://github.com/seqyuan/anno_papaer.git
          mv sphinxbook/docs ./
          rm -r sphinxbook
          mv anno_papaer/docs/* ./docs
          rm -r anno_papaer
          git remote add target https://github.com/seqyuan/paper_pages.git
          git add -A
          git commit -m "..."
          git push origin gh-pages
